## tns-server docker compose file

version: '2'
services:
  tns:
    image: docker.sec.samsung.net:5000/edge/system-tns-server-go/ubuntu_x86_64
    ports:
      - "48323:48323"
    volumes:
      - "/tns-server/data/db:/data/db"
    container_name: tns-server
...

