swagger: '2.0'
info:
  title: TNS Server REST APIs
  description: >-
    TNS Server REST APIs
  version: v1-20180307
schemes:
  - http
tags:
  - name: REST APIs
    description: TNS REST APIs

paths:
  '/api/v1/tns/topic':
    get:
      tags:
        - REST APIs
      description: |
        Request get all lists of tnsdb
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: All tns data get succeeds
          schema:
            $ref: '#/definitions/response_of_discoverall'
    post:
      tags:
        - REST APIs
      description: |
        register topic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: topic
          in: path
          description: topic for register
          required: true
          type: string
        - name: endpoint
          in: path
          description: endpoint(IP,port) of publisher
          required: true
          type: string
        - name: service_id
          in: path
          description: Service ID of publisher
          required: true
          type: string          
      responses:
        '200':
          description: Topic register Succeed
  '/api/v1/tns/topic/{arg}':
    get:
      tags:
        - REST APIs
      description: |
        Topic Resolution 
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: arg
          in: path
          description: topic for resolution 1. topic name is complete form("SEVT/2F13B/S9/Cam_tester_25")-> it returns endpoint of topic 2. single wildcard("SEVT/2F13B/+/Cam_tester_25")-> it returns all endpoints including '+' wildcard 3. multi wildcard("SEVT/2F13B/S9/*")-> it returns all endpoints including '*' wildcard. more info about topic convention -> http://suprem.sec.samsung.net/confluence/display/ILIOTC/995.+Topic+Naming+Convention+Guide    
          required: true
          type: string
      responses:
        '200':
          description: resolution succeeds
          schema:
            $ref: '#/definitions/resolution'
  '/api/v1/tns/health':
    post:
      tags:
        - REST APIs
      description: |
        register topic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: topic
          in: path
          description: topic for register
          required: true
          type: string
      responses:
        '200':
          description: Health Check Succeed
            
definitions:

  tnsdata:
    required:
      - topic
      - endpoint
      - service_id
    properties:
      topic:
        type: string
        example: SEVT/2F13B/S9/Cam_tester_25
      endpoint:
        type: string
        example: 10.112.34.114:3434
      service_id:
        type: string
        example: falhkgjasdlkgjspdaijsajaslgalksd
  resolution:
    required:
      - endpoint
    properties:
      endpoint:
        type: string
        example: 10.112.34.114:3434
  response_of_discoverall:
    $ref: '#/definitions/tnsdata'

