swagger: '2.0'
info:
  title: TNS Server REST APIs
  description: >-
    TNS Server REST APIs
  version: v1-20180307
schemes:
  - http
tags:
  - name: REST APIs
    description: TNS REST APIs

paths:
  '/api/v1/tns/topic':
    get:
      tags:
        - REST APIs
      description: |
        Request get all lists of tnsdb port:48323
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: TNS system will return topics, you can also query with this GET REST api like this /tns/topic?topic=/test/a then TNS system returns all topics including "/test/a"
          schema:
            $ref: '#/definitions/response_of_discoverall'
    post:
      tags:
        - REST APIs
      description: |
        register topic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: topic
          in: path
          description: topic for register port:48323
          required: true
          type: string
        - name: endpoint
          in: path
          description: endpoint(IP,port) of publisher
          required: true
          type: string
        - name: service_id
          in: path
          description: Service ID of publisher
          required: true
          type: string          
      responses:
        '200':
          description: Topic register Succeed

  '/api/v1/tns/keepalive':
    post:
      tags:
        - REST APIs
      description: |
        send keep alive topics in Json format port:48324
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: topic
          in: path
          description: topic for register
          required: true
          type: string
      responses:
        '200':
          description: Success
    
definitions:

  tnsdata:
    required:
      - topic
      - endpoint
      - service_id
    properties:
      topic:
        type: string
        example: SEVT/2F13B/S9/Cam_tester_25
      endpoint:
        type: string
        example: 10.112.34.114:3434
      service_id:
        type: string
        example: falhkgjasdlkgjspdaijsajaslgalksd
  resolution:
    required:
      - endpoint
    properties:
      endpoint:
        type: string
        example: 10.112.34.114:3434
  response_of_discoverall:
    $ref: '#/definitions/tnsdata'

